Omou Payments
omou-org/mainframe pull request #11
Opened 2019-08-17 19:31 UTC by haochiencho

### Notes 

Added backend support for course sessions, student payments, session payments, and promos

### Testing
Manually tested endpoints using Swagger

2019-08-25 16:44 UTC, jerrylinew requested changes
View comments for things to address.

Can we split something like this into multiple smaller diffs next time? Super long diffs such as this are fairly hard to review.

2019-08-25 16:44 UTC, jerrylinew commented on course/models.py
> +    price = models.DecimalField(max_digits=6, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
price should be associated with the course, not the individual session. Also, the session model has already been added in the scheduler app

2019-08-25 16:44 UTC, jerrylinew commented on course/models.py
> +    price = models.DecimalField(max_digits=6, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
rebase onto master to merge

2019-08-25 16:44 UTC, jerrylinew commented on course/serializers.py
> +class SessionSerializer(serializers.ModelSerializer):
same as above

2019-08-25 16:44 UTC, jerrylinew commented on payment/models.py
> +    # Many-to-one relationship with Student
* with Payment

2019-08-25 16:44 UTC, jerrylinew commented on payment/models.py
> +    date_time = models.DateTimeField(auto_now=True)
let's be consistent with the other models: use created_at and updated_at (with auto_now=True for updated_at and auto_now_add=True for created_at)

2019-08-25 16:44 UTC, jerrylinew commented on payment/models.py
> +    date_time = models.DateTimeField(auto_now=True)
same as above: use created_at and updated_at

2019-08-25 16:44 UTC, jerrylinew commented on payment/urls.py
> +router.register(r'student', PaymentViewSet)
r'payment'?

2019-08-25 16:44 UTC, jerrylinew commented on promo/models.py
> +
Need a promo description field to explain what this promo is for.

2019-08-27 02:16 UTC, haochiencho commented
> View comments for things to address.
> 
> Can we split something like this into multiple smaller diffs next time? Super long diffs such as this are fairly hard to review.

2019-08-27 02:21 UTC, haochiencho commented
> View comments for things to address.
> 
> Can we split something like this into multiple smaller diffs next time? Super long diffs such as this are fairly hard to review.

This pull request contains 8 commits, which have smaller changes. Should we have one pull request per commit or group them together?

2019-08-27 02:22 UTC, haochiencho commented on promo/models.py
> +
Good point. I will add that

2019-08-27 02:23 UTC, haochiencho commented on payment/models.py
> +    date_time = models.DateTimeField(auto_now=True)
got it

2019-08-27 02:33 UTC, haochiencho commented on payment/urls.py
> +router.register(r'student', PaymentViewSet)
It should either be student or nothing so the endpoint will be:

/payment/student
or
/payment

2019-08-27 02:33 UTC, haochiencho commented on payment/models.py
> +    date_time = models.DateTimeField(auto_now=True)
yep

2019-08-27 02:36 UTC, haochiencho commented on course/models.py
> +    price = models.DecimalField(max_digits=6, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
I added price to sessions so we can use it for both courses and tutoring sessions. Otherwise, we would need to setup both course and session payments/prices

2020-02-09 23:31 UTC, closed without merging